# Generated by Django 5.2.7 on 2025-10-18 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, help_text="用户名", max_length=50, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, help_text="邮箱", max_length=254, unique=True
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        db_index=True, help_text="用户ID", max_length=50, unique=True
                    ),
                ),
                ("passwd", models.CharField(help_text="加密后的密码", max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理员"), ("user", "普通用户"), ("guest", "访客")],
                        db_index=True,
                        default="user",
                        help_text="用户角色",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="用户是否激活"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, help_text="是否为员工")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, help_text="是否为超级用户"),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, help_text="最后登录时间", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="更新时间")),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["userid"], name="users_userid_cd8762_idx"),
                    models.Index(fields=["role"], name="users_role_0ace22_idx"),
                    models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
                    models.Index(
                        fields=["created_at"], name="users_created_6541e9_idx"
                    ),
                    models.Index(
                        fields=["userid", "role"], name="users_userid_71c107_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("register", "注册"),
                            ("update_profile", "更新资料"),
                            ("change_password", "修改密码"),
                            ("deactivate", "停用账户"),
                            ("activate", "激活账户"),
                        ],
                        db_index=True,
                        help_text="操作类型",
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP地址", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="用户代理")),
                ("success", models.BooleanField(default=True, help_text="操作是否成功")),
                ("error_message", models.TextField(blank=True, help_text="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户活动",
                "verbose_name_plural": "用户活动",
                "db_table": "user_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="user_activi_user_id_c742e0_idx",
                    ),
                    models.Index(
                        fields=["action"], name="user_activi_action_b4118c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="user_activi_created_9fa3ca_idx"
                    ),
                    models.Index(
                        fields=["user", "action"], name="user_activi_user_id_46cf8f_idx"
                    ),
                ],
            },
        ),
    ]
