# Generated by Django 5.2.7 on 2025-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "超级管理员"),
                    ("competition_admin", "学院学科竞赛管理员"),
                    ("teacher", "学院教师"),
                    ("student", "学院学生"),
                ],
                db_index=True,
                default="student",
                help_text="用户角色",
                max_length=30,
            ),
        ),
    ]
