# Generated by Django 5.2.7 on 2025-10-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_admin",
            field=models.BooleanField(
                db_index=True, default=False, help_text="是否为系统根管理员"
            ),
        ),
    ]
